language: python
python:
  - 2.7
notifications:
  email:
    - tbarbugli@gmail.com
    - guyon@fashiolista.com
    - thierryschellenbach@gmail.com
env:
  - TEST_TO_RUN=py.test feedly/tests -sl --tb=short --cov coveralls --cov-report term-missing --cov feedly
  - TEST_TO_RUN=python pinterest_example/manage.py test core
services:
  - redis # will start rabbitmq-server
# based on https://github.com/travis-ci/travis-ci/issues/1203
before_install:
  - test -f "/usr/local/cassandra/etc/cassandra-env.sh" && sudo rm -f /usr/local/cassandra/conf/cassandra-env.sh && sudo ln -s /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh
  - sudo service cassandra start
  - sleep 3
install:
  - pip install pep8 --use-mirrors
  - pip install coverage
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
  - pip install -r pinterest_example/requirements/$REQUIREMENTS.txt --use-mirrors -I
before_script:
  #- "pep8 --exclude=migrations --ignore=E501,E225 feedly"
script:
  # this looks good
  - pip install -e .
  - $TEST_TO_RUN
after_success:
  - coveralls
