language: python
python:
  - 2.7
notifications:
  email:
    - tbarbugli@gmail.com
    - thierryschellenbach@gmail.com
services:
  - redis
before_install:
  - sudo apt-get install libev4 libev-dev
  - test -f "/usr/local/cassandra/etc/cassandra-env.sh" && sudo rm -f /usr/local/cassandra/conf/cassandra-env.sh && sudo ln -s /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh
  - sudo service cassandra start
  - git clone https://github.com/tbarbugli/feedly_pin.git pinterest_example
  - sleep 3
install:
  - easy_install -U distribute
  - pip install pep8 --use-mirrors
  - pip install coverage
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
  - pip install -r pinterest_example/requirements/testing.txt --use-mirrors -I
script:
  - pip install -e .
  - py.test -sl --tb=short --cov coveralls --cov-report term-missing --cov feedly feedly/tests
  - python pinterest_example/manage.py test core
after_success:
  - coveralls
