language: python
python:
  - 2.7
notifications:
  email:
    - tbarbugli@gmail.com
    - thierryschellenbach@gmail.com
services:
  - redis
  - cassandra
before_install:
  - sudo apt-get install libev4 libev-dev
  - git clone https://github.com/tbarbugli/feedly_pin.git pinterest_example
install:
  - easy_install -U distribute
  - pip install pep8 --use-mirrors
  - pip install coverage
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -e . --use-mirrors
  - pip install -r pinterest_example/requirements/testing.txt --use-mirrors -I
script:
  - py.test -sl --tb=short --cov coveralls --cov-report term-missing --cov feedly feedly/tests
  - python pinterest_example/manage.py test core
after_success:
  - coveralls
