language: python
python:
  - 2.7
notifications:
  email:
    - tbarbugli@gmail.com
    - guyon@fashiolista.com
    - thierryschellenbach@gmail.com
env:
  - REQUIREMENTS=testing
services:
  - redis # will start redis server
# based on https://github.com/travis-ci/travis-ci/issues/1203
before_install:
  - sudo apt-get install libev4 libev-dev
  - test -f "/usr/local/cassandra/etc/cassandra-env.sh" && sudo rm -f /usr/local/cassandra/conf/cassandra-env.sh && sudo ln -s /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh
  - sudo service cassandra start
  - sleep 3
install:
  - easy_install -U distribute
  - pip install pep8 --use-mirrors
  - pip install coverage
  - pip install https://github.com/dcramer/pyflakes/tarball/master
# cqlengine forking problems
  - pip uninstall cqlengine
  - python setup.py install
  - pip install -r pinterest_example/requirements/$REQUIREMENTS.txt --use-mirrors -I
before_script:
  #- "pep8 --exclude=migrations --ignore=E501,E225 feedly"
script:
  - pip install -e .
  - py.test -sl --tb=short --cov coveralls --cov-report term-missing --cov feedly feedly/tests
  - python pinterest_example/manage.py test core
after_success:
  - coveralls
