language: python
python:
  - 2.7
  - 3.4
sudo: false
addons:
  apt:
    packages:
    - libev4
    - libev-dev
notifications:
  email:
    - tbarbugli@gmail.com
    - thierryschellenbach@gmail.com
cache:
  directories:
    - $HOME/.pip-cache/
env:
  - CASSANDRA_DRIVER="2.7.2"
  - CASSANDRA_DRIVER="3.0.0"
services:
  - redis
  - cassandra
before_install:
  - git clone https://github.com/tbarbugli/stream_framework_example.git pinterest_example
before_script:
  - echo 'DROP KEYSPACE test_stream_framework;' | /usr/local/cassandra/bin/cqlsh;
install:
  - easy_install -U distribute
  - pip install -e .
  - echo "CREATE KEYSPACE stream_framework WITH REPLICATION = { 'class':'SimpleStrategy', 'replication_factor':1 };" | cqlsh
  - pip freeze
  - pip install cassandra-driver==$CASSANDRA_DRIVER
script:
  - py.test -sl --tb=short stream_framework/tests
