language: python
python:
  - 2.7
notifications:
  email:
    - tbarbugli@gmail.com
    - thierryschellenbach@gmail.com
cache:
  directories:
    - $HOME/.pip-cache/
services:
  - redis
  - cassandra
before_install:
  - sudo apt-get install libev4 libev-dev
before_script:
  - echo 'DROP KEYSPACE test_stream_framework;' | /usr/local/cassandra/bin/cqlsh;
  - sudo rm -rf /var/lib/cassandra/data/test_stream_framework
install:
  - easy_install -U distribute
  - pip install -e . --download-cache $HOME/.pip-cache
script:
  - py.test -sl --tb=short stream_framework/tests